apiVersion: v1
kind: Service
metadata:
  name: kube-demo-svc
  labels:
    app: kube-demo
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 30010
      protocol: TCP
  selector:
    app: kube-demo
