apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-demo
  name: kube-demo-deploy
  namespace: kube-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-demo
  template:
    metadata:
      labels:
        app: kube-demo
    spec:
      containers:
        - image: zabsdockerhub/kube-demo:1.3
          name: kube-demo
          ports:
            - containerPort: 9090
              name: kube-demo
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
          env:
            # Define the environment variable
            - name: DEMO_STRING # Notice that the case is different here
              # from the key name in the ConfigMap.
              valueFrom:
                configMapKeyRef:
                  name: kube-demo-config           # The ConfigMap this value comes from.
                  key: hello_message # The key to fetch.